// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkMZcb2regM7K7UAKgpY0mS0JW0_ga7Ok',
    appId: '1:338484015980:web:4ac1f8f091c052f3ec3949',
    messagingSenderId: '338484015980',
    projectId: 'ecommerce-a09dc',
    authDomain: 'ecommerce-a09dc.firebaseapp.com',
    storageBucket: 'ecommerce-a09dc.firebasestorage.app',
    measurementId: 'G-V94681SR4B',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXHaD3rjKY9m24ZsaaWCoxNxAqfqFGi1s',
    appId: '1:338484015980:ios:982edd4f030099deec3949',
    messagingSenderId: '338484015980',
    projectId: 'ecommerce-a09dc',
    storageBucket: 'ecommerce-a09dc.firebasestorage.app',
    androidClientId: '338484015980-p4s8hm67dt28gin4rn88odp5jcqre55q.apps.googleusercontent.com',
    iosClientId: '338484015980-qcruljuovm32d2jrjovpsno8vdc3agjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXHaD3rjKY9m24ZsaaWCoxNxAqfqFGi1s',
    appId: '1:338484015980:ios:982edd4f030099deec3949',
    messagingSenderId: '338484015980',
    projectId: 'ecommerce-a09dc',
    storageBucket: 'ecommerce-a09dc.firebasestorage.app',
    androidClientId: '338484015980-p4s8hm67dt28gin4rn88odp5jcqre55q.apps.googleusercontent.com',
    iosClientId: '338484015980-qcruljuovm32d2jrjovpsno8vdc3agjg.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkMZcb2regM7K7UAKgpY0mS0JW0_ga7Ok',
    appId: '1:338484015980:web:a0f80b6fcd744ebfec3949',
    messagingSenderId: '338484015980',
    projectId: 'ecommerce-a09dc',
    authDomain: 'ecommerce-a09dc.firebaseapp.com',
    storageBucket: 'ecommerce-a09dc.firebasestorage.app',
    measurementId: 'G-VE04M09NJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBST5QKOSo1YPs_jACfxbZ30LTSVltRx_I',
    appId: '1:338484015980:android:2071ad785af70f1dec3949',
    messagingSenderId: '338484015980',
    projectId: 'ecommerce-a09dc',
    storageBucket: 'ecommerce-a09dc.firebasestorage.app',
  );

}